sudo: required

language: node_js

node_js:
  - "lts/*"

services:
  - docker

services:
  - docker

before_install:
  - docker-compose -f test/docker-compose-testbed.yaml up -d
  - docker ps
  - sleep 15
  - docker logs freeswitch-sut

script:
  - npm test
  